//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemplateDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public string CompanyName { get; set; }
        public string Name { get; set; }
        public int Sex { get; set; }
        public string Email { get; set; }
        public string ContactPhone { get; set; }
        public int ContactEnum { get; set; }
        public int ContactStatus { get; set; }
        public string Budget { get; set; }
        public string OnlineDate { get; set; }
        public string Demand { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
    }
}
