//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemplateDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceItem
    {
        public int ServiceItemId { get; set; }
        public string ServiceItemName { get; set; }
        public string ImageName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public string IconName { get; set; }
        public string Mode { get; set; }
    }
}
