//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemplateDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebConfig
    {
        public int Id { get; set; }
        public string WebName { get; set; }
        public string ServiceMail { get; set; }
        public string Copyright { get; set; }
        public string SystemEmailName { get; set; }
        public string SystemEmail { get; set; }
        public string meta_title { get; set; }
        public string meta_keyword { get; set; }
        public string meta_description { get; set; }
        public string meta_url { get; set; }
        public string meta_image { get; set; }
        public string CompanyAddress { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public string TaxIDNumber { get; set; }
        public string Phone { get; set; }
    }
}
